"""
Repository hygiene guards.

This repository has a demonstrated history of committing its own runtime
output: `chore: add gauntlet test artifacts, databases, and CI workflow` added
32 SQLite databases, 12 gauntlet report JSONs, a 4.6 MB proof-of-work log and a
32 MB DRAGON state snapshot -- 57 MB of generated data in a repo whose actual
source is under 2 MB. `.gitignore` already listed `proof_of_work_log.jsonl` at
the time, and it was tracked anyway, because ignore rules never apply to files
that are already in the index.

So these tests check two separate properties, and the second is the one that
matters:

1. Nothing matching an artifact pattern is currently tracked.
2. Every artifact pattern is actually covered by `.gitignore`, so a regenerated
   file cannot be swept back in by `git add -A`.

Property 1 alone would pass the day after a cleanup and fail again the day
after the next test run. Property 2 is what makes the cleanup stick.

Also guarded: no single tracked file over 1 MB. The largest legitimate files
are a 867 KB seed list and a 476 KB documentation image, so the threshold sits
above both and below every artifact that was removed.
"""

import fnmatch
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

MAX_TRACKED_BYTES = 1_000_000

# pattern -> a probe path used to verify .gitignore actually covers it
ARTIFACT_PATTERNS = {
    "*.db": "probe_artifact.db",
    "*.db-wal": "probe_artifact.db-wal",
    "*.db-shm": "probe_artifact.db-shm",
    "gauntlet_report_*.json": "gauntlet_report_deadbeef.json",
    "dragon/pool_state.json": "dragon/pool_state.json",
    "*_dragon.json": "probe_dragon.json",
    "*.jsonl": "probe_artifact.jsonl",
    "batch_log.txt": "batch_log.txt",
    "station_keys.json": "station_keys.json",
    # This is the pattern that leaked. The old rule was the bare filename, which
    # matches nothing but itself, so all 16 per-database sidecars that
    # IntelligencePool._key_file writes as `<db>.station_keys.json` were tracked
    # and publicly fetchable -- 14 of them carrying an `aboyeur` signing key.
    "*.station_keys.json": "gauntlet_phase1.db.station_keys.json",
    "*.station_keys.json.enc": "probe.db.station_keys.json.enc",
    "station_keys.json.enc": "station_keys.json.enc",
}

# Curated transcripts kept as documentation. `examples/five_target_spread.log`
# is a 2 KB sample of the 5-target demo run, not generated output, so the log
# rule deliberately does not reach into examples/.
LOG_ALLOWLIST = ("examples/",)


def _git(*args):
    return subprocess.run(
        ["git", *args], cwd=str(REPO_ROOT), capture_output=True, text=True
    )


@pytest.fixture(scope="module")
def tracked_files():
    """Files in the index. Skips cleanly when run outside a git checkout,
    e.g. against an installed wheel, where there is no repository to audit.
    """
    if not (REPO_ROOT / ".git").exists():
        pytest.skip("not a git checkout; nothing to audit")
    result = _git("ls-files")
    if result.returncode != 0:
        pytest.skip(f"git ls-files failed: {result.stderr.strip()}")
    return [line for line in result.stdout.splitlines() if line.strip()]


def _matches_any(path, patterns):
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def test_no_tracked_sqlite_databases(tracked_files):
    dbs = [f for f in tracked_files if f.endswith((".db", ".db-wal", ".db-shm"))]
    assert not dbs, (
        f"{len(dbs)} SQLite files are tracked ({dbs[:5]}...). These are pool "
        f"and gauntlet state, generated at runtime; CI uploads failures as "
        f"workflow artifacts instead."
    )


def test_no_tracked_runtime_reports_or_logs(tracked_files):
    patterns = (
        "gauntlet_report_*.json",
        "*_dragon.json",
        "dragon/pool_state.json",
        "*.jsonl",
        "batch_log.txt",
        "*.log",
    )
    offenders = [
        f
        for f in tracked_files
        if _matches_any(f, patterns)
        and not f.startswith(LOG_ALLOWLIST)
    ]
    assert not offenders, (
        f"tracked runtime output: {offenders[:8]}. Curated transcripts under "
        f"{LOG_ALLOWLIST} are exempt; everything else is generated by a run."
    )


def test_no_tracked_station_keys(tracked_files):
    """These are live HMAC write-auth credentials. They were committed in
    plaintext and remain retrievable from history at any commit before the
    removal, so keeping them out of the index is the minimum, not the fix.
    """
    patterns = ("station_keys.json", "*station_keys.json*", "*.enc", "*.key")
    offenders = [f for f in tracked_files if _matches_any(f, patterns)]
    assert not offenders, f"credential material is tracked: {offenders}"


def test_no_tracked_file_exceeds_the_size_ceiling(tracked_files):
    oversized = []
    for rel in tracked_files:
        path = REPO_ROOT / rel
        if not path.exists():
            continue
        size = path.stat().st_size
        if size > MAX_TRACKED_BYTES:
            oversized.append((rel, size))

    assert not oversized, (
        "tracked files over "
        f"{MAX_TRACKED_BYTES // 1000} KB: "
        + ", ".join(f"{r} ({s / 1048576:.1f} MB)" for r, s in oversized)
    )


@pytest.mark.parametrize("pattern,probe", sorted(ARTIFACT_PATTERNS.items()))
def test_gitignore_covers_the_pattern(pattern, probe):
    """The cleanup only holds if regeneration cannot re-track the artifact.

    This is the guard the original `.gitignore` would have failed: it listed
    `proof_of_work_log.jsonl` while that file sat in the index, so the rule was
    inert. Checking `git check-ignore` against a probe path verifies the rule
    is live rather than merely written down.
    """
    result = _git("check-ignore", "-q", probe)
    assert result.returncode == 0, (
        f"{probe!r} is not ignored, so the pattern {pattern!r} is not enforced "
        f"-- a regenerated artifact would be picked up by `git add -A`"
    )


def test_removing_artifacts_does_not_delete_them_from_disk():
    """Untracking is `git rm --cached`, not `git rm`.

    dragon/pool_state.json is fetched by dragon/index.html and written by
    batch_run.py; the gauntlet databases are read by the CI artifact-upload
    step when a run fails. Deleting them from a working checkout would break
    both, so the cleanup must have left them in place.
    """
    for rel in ("dragon/pool_state.json",):
        path = REPO_ROOT / rel
        if path.exists():
            result = _git("check-ignore", "-q", rel)
            assert result.returncode == 0, (
                f"{rel} exists on disk but is not ignored -- it would be "
                f"re-added by `git add -A`"
            )
